#!/usr/bin/env python3
import argparse
import json
import sys


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render Jira ADF document with AI attribution panel."
    )
    parser.add_argument("--text", help="Plain-text body for the first paragraph")
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read plain-text body from stdin instead of --text",
    )
    args = parser.parse_args()

    if args.stdin:
        body = sys.stdin.read().strip()
    else:
        body = (args.text or "").strip()

    if not body:
        print("error: provide --text or --stdin with non-empty content", file=sys.stderr)
        return 1

    doc = {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": body}],
            },
            {
                "type": "panel",
                "attrs": {"panelType": "warning"},
                "content": [
                    {
                        "type": "paragraph",
                        "content": [
                            {"type": "text", "text": "🤖 Generated by AI"}
                        ],
                    }
                ],
            },
        ],
    }

    json.dump(doc, sys.stdout, ensure_ascii=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
