#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path


MIN_PYTHON = (3, 12)


def require_python_version() -> None:
    if sys.version_info < MIN_PYTHON:
        print("error: Python 3.12 or later is required", file=sys.stderr)
        raise SystemExit(1)


def read_text(path: str | None) -> str:
    if path:
        return Path(path).read_text(encoding="utf-8")
    return sys.stdin.read()


def main() -> int:
    require_python_version()

    parser = argparse.ArgumentParser(
        description="Render Jira ADF for dashboard evidence with operation id and stack trace expand."
    )
    parser.add_argument("--operation-id", required=True, help="Dashboard operation id")
    parser.add_argument("--message-file", help="File containing any_message or stack trace")
    parser.add_argument(
        "--intro",
        default="Dashboard failure from production monitoring.",
        help="Intro paragraph",
    )
    args = parser.parse_args()

    message = read_text(args.message_file).strip()
    if not message:
        print("error: provide stack trace through --message-file or stdin", file=sys.stderr)
        return 1

    doc = {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": args.intro}],
            },
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": f"operation_id: {args.operation_id}"}],
            },
            {
                "type": "expand",
                "attrs": {"title": "any_message"},
                "content": [
                    {
                        "type": "codeBlock",
                        "attrs": {"language": "text"},
                        "content": [{"type": "text", "text": message}],
                    }
                ],
            },
            {
                "type": "panel",
                "attrs": {"panelType": "warning"},
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": "🤖 Generated by AI"}],
                    }
                ],
            },
        ],
    }

    json.dump(doc, sys.stdout, ensure_ascii=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
