import json

from helpers import call_main, load

SCRIPT_UNDER_TEST = "skills/mpt-ext-tool-jira-workitem-ops/scripts/render_adf_with_attribution.py"
mod = load(SCRIPT_UNDER_TEST)


def test_text_renders_doc_with_attribution():
    code, out, _ = call_main(mod, ["--text", "Update details"])
    assert code == 0
    doc = json.loads(out)
    assert doc["type"] == "doc"
    assert "Generated by AI" in out


def test_stdin_body():
    code, out, _ = call_main(mod, ["--stdin"], stdin="Body from stdin")
    assert code == 0
    assert json.loads(out)["type"] == "doc"
    assert "Body from stdin" in out


def test_empty_body_errors():
    code, _, err = call_main(mod, [])
    assert code == 1 and "error" in err
