import json

from helpers import call_main, load

SCRIPT_UNDER_TEST = "skills/mpt-ext-task-apply-dashboard-jira-decision/scripts/render_dashboard_adf.py"
mod = load(SCRIPT_UNDER_TEST)


def test_renders_doc_with_evidence_from_stdin():
    code, out, _ = call_main(mod, ["--operation-id", "OP-1"], stdin="NullReferenceException at Foo.Bar")
    assert code == 0
    doc = json.loads(out)
    assert doc["type"] == "doc"
    assert "OP-1" in out
    assert "Generated by AI" in out


def test_custom_intro_from_message_file(tmp_path):
    msg = tmp_path / "m.txt"
    msg.write_text("boom")
    code, out, _ = call_main(mod, ["--operation-id", "OP-2", "--message-file", str(msg), "--intro", "Custom intro"])
    assert code == 0
    assert "Custom intro" in out


def test_empty_message_errors():
    code, _, err = call_main(mod, ["--operation-id", "OP-1"], stdin="")
    assert code == 1 and "error" in err
